sidecar:
  datasources:
    enabled: true
  dashboards:
    enabled: true
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: "http://loki-gateway"
      version: 1
      uid: loki
    - name: Tempo
      type: tempo
      url: "http://tempo:3100"
      access: proxy
      basicAuth: false
      jsonData:
        tracesToLogsV2:
          datasourceUid: 'loki'
          spanStartTimeShift: '-1s'
          spanEndTimeShift: '1s'
          # tags: ['namespace', 'pod']
          filterByTraceID: false
          filterBySpanID: false
          customQuery: true
          query: '{namespace="$${__span.tags.namespace}", pod="$${__span.tags.pod}"}'
        tracesToMetrics:
          datasourceUid: 'mimir'
          spanStartTimeShift: '1h'
          spanEndTimeShift: '-1h'
          # tags: "[{ key: 'namespace'}, { key: 'pod'}]"
          queries:
            - name: 'Sample query'
              query: 'sum(rate(process_runtime_jvm_cpu_utilization{$$__tags}[5m]))'
      uid: tempo
    - name: Mimir
      type: prometheus
      url: "http://mimir-nginx.observability.svc/prometheus"
      uid: mimir
