apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - otel

configMapGenerator:
  - name: host-metrics-dashboard
    files:
      - ./try-me/observability/dashboards/host-metrics-dashboard.json
  - name: kubernetes-nodes-dashboard
    files:
      - ./try-me/observability/dashboards/kubernetes-nodes-dashboard.json
  - name: kubernetes-pods-dashboard
    files:
      - ./try-me/observability/dashboards/kubernetes-pods-dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
