apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: autoinstrumentation
spec:
  exporter:
    endpoint: http://jvm-collector-collector.observability.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
