apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: autoinstrumentation
spec:
  exporter:
    endpoint: http://java-collector:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
