apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: jvm-otel
  namespace: observability
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
      resource:
        attributes:
          - action: insert
            key: loki.resource.labels
            value: service.name, k8s.pod.name, k8s.container.name, k8s.namespace.name

    exporters:
      prometheus:
        endpoint: prometheus-pushgateway.observability.svc.cluster.local:9091
      loki:
        endpoint: "http://loki-gateway.observability/loki/api/v1/push"

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [resource]
          exporters: [loki]
