apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: jvm-autoinstrumentation
spec:
  exporter:
    endpoint: http://jvm-otel-collector.observability.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    env:
      - name: OTLP_METRICS_EXPORTER
        value: otlp
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: service.name=backend2-service,service.namespace=tutorial-application
