apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: jvm-metrics-collector
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      prometheus:
        endpoint: kube-prometheus-stack-prometheus.monitoring:8889

    service:
      pipelines:
        # traces:
        #   receivers: [otlp]
        #   processors: [memory_limiter, batch]
        #   exporters: [debug]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheus]
        # logs:
        #   receivers: [otlp]
        #   processors: [memory_limiter, batch]
        #   exporters: [debug]
