apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jvm-otel-collector-targetallocator
subjects:
  - kind: ServiceAccount
    name: jvm-otel-collector-targetallocator
    namespace: observability
roleRef:
  kind: ClusterRole
  name: jvm-opentelemetry-targetallocator-role
  apiGroup: rbac.authorization.k8s.io
