minio:
  enabled: true
read:
  replicas: 1
write:
  replicas: 1
backend:
  replicas: 1
chunksCache:
  enabled: false

loki:
  auth_enabled: false
  storage_config:
    tsdb_shipper:
      active_index_directory: /loki/index
      cache_location: /loki/index_cache
      cache_ttl: 24h

  schemaConfig:
    configs:
      - from: "2020-04-18"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h
