server:
  extraFlags:
    - enable-feature=otlp-write-receiver
    - web.enable-lifecycle

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
