{
 "title": "Kubernetes / Views / Nodes",
 "description": "This is a modern 'Nodes View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "opentelemetry"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"(?i:($node))\"}, instance)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(container_cpu_time,host_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU  Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(host_name) (irate(system_cpu_time{host_name=\"$host\", state!=\"idle\"}[5m])) / on(host_name) group_left sum by (host_name)((irate(system_cpu_time{host_name=\"$host\"}[5m]))))"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_memory_usage{host_name=\"${host}\", state=\"used\"}) / sum(system_memory_limit{host_name=\"$host\"})"
    }
   ]
  },
  {
   "title": "Pods on node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=\"$host\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "List of pods on node ($host)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_info{node=\"$host\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_logical_count{ host_name=\"${host}\"}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_memory_usage{node=\"$host\", cluster=\"$cluster\", state=\"used\"})"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_memory_limit{host_name=\"$host\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otelcol_process_uptime{node=\"${host}\"}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_cpu_time{node=\"$host\", cluster=\"$cluster\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (k8s_pod_memory_usage{node=\"$host\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "system_cpu_load_average_15m{node=\"$host\", cluster=\"$cluster\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "15m"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network usage (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(system_network_io{node=\"$host\", cluster=\"$cluster\", direction=\"receive\"}[$__rate_interval]))",
       "legendFormat": "In"
      },
      {
       "expr": "- sum(rate(system_network_io{node=\"$host\", cluster=\"$cluster\", direction=\"transmit\"}[$__rate_interval]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Network errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(system_network_errors{node=\"$host\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "In"
      },
      {
       "expr": "sum(rate(system_network_errors{node=\"$host\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Network usage (packet/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(system_network_packets{node=\"$host\", cluster=\"$cluster\", direction=\"receive\"}[$__rate_interval]))",
       "legendFormat": "In"
      },
      {
       "expr": "-sum(rate(system_network_packets{node=\"$host\", cluster=\"$cluster\", direction=\"transmit\"}[$__rate_interval]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Network total drops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(system_network_dropped{node=\"$host\", cluster=\"$cluster\", direction=\"receive\"}[$__rate_interval]))",
       "legendFormat": "In"
      },
      {
       "expr": "- sum(rate(system_network_dropped{node=\"$host\", cluster=\"$cluster\", direction=\"transmit\"}[$__rate_interval]))",
       "legendFormat": "Out"
      }
     ]
    }
   ]
  },
  { "title": "Kubernetes Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Persistent Volumes - Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(persistentvolumeclaim) ((k8s_volume_capacity{node=\"$host\", cluster=\"$cluster\"}) - (k8s_volume_available{node=\"$host\", cluster=\"$cluster\"}) )/ sum by(persistentvolumeclaim) (k8s_volume_capacity{node=\"$host\", cluster=\"$cluster\"})",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Usage in GB",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(persistentvolumeclaim) ((k8s_volume_capacity{node=\"$host\", cluster=\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(persistentvolumeclaim) (k8s_volume_inodes_used{node=\"$host\", cluster=\"$cluster\"}) * 100) / sum by(persistentvolumeclaim) (k8s_volume_inodes{node=\"$host\", cluster=\"$cluster\"})",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  { "title": "Node Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "FS usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  sum(system_filesystem_usage{state=\"used\", node=\"${host}\"}) by (instance) / \n  sum(system_filesystem_usage{state=~\"used|free\", node=\"${host}\"}) by (instance)\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FS inode usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  sum(system_filesystem_inodes_usage{state=\"used\", node=\"${host}\"}) by (instance) / \n  sum(system_filesystem_inodes_usage{state=~\"used|free\", node=\"${host}\"}) by (instance)\n)\n",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Reads by disk (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(system_disk_io{host_name=\"${host}\", direction=\"read\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Writes by disk (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(system_disk_io{host_name=\"${host}\", direction=\"write\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Completed reads by disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "read/s" } },
   "targets": [
    {
     "expr": "irate(system_disk_operations{host_name=\"${host}\", direction=\"read\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Completed writes by disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "write/s" } },
   "targets": [
    {
     "expr": "irate(system_disk_operations{host_name=\"${host}\", direction=\"write\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk(s) io/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "io/s" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_now{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]) ",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "FS - Device Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_device_error{instance=\"$instance\", cluster=\"$cluster\"}) by (mountpoint)",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  }
 ]
}