name: Pulumi CI/CD with KIND

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.5.0'
    
    - name: Install Dependencies
      run: |
        npm install -g npm@>=10.0.0
        npm install
      working-directory: ./deploy/observability

    - name: Install ESLint
      run: npm install eslint

    # - name: Lint JavaScript files
    #   run: npx eslint .  # Adjust the path as needed
    #   working-directory: ./deploy/observability

    - name: Create a KIND Cluster
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        kind create cluster

    - name: Install Pulumi
      run: |
        curl -fsSL https://get.pulumi.com | sh
        echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

    - name: Run Pulumi Up
      env:
        PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      run: |
        echo "$PULUMI_CONFIG_PASSPHRASE"
        pulumi login --local
        pulumi stack init localstack
      working-directory: ./deploy/observability

    - name: Destroy Pulumi Resources
      run: |
        pulumi destroy --yes

    - name: Destroy the KIND Cluster
      if: always()
      run: |
        kind delete cluster

